### ISSUE TITLE
Does not pull Index Information

### ISSUE THREAD

**Issue by jolwaterman** [Dede333/VB_DISMGUI#3]
This application doesn't pull the wim index number.

Also, in the other tabs, the dropdown displays nothing after the wim is mounted

**Comment by Dede333** [comment]
Hello,
Are you sure that you used this version ?:
https://github.com/Dede333/VB_DISMGUI/releases/tag/10
Because the application of mikecel79 not have this option (it's a hard coding index).
In the other tabs, clic on "Refresh mounted image" button and select list "Use mounted image" (you can see all images mounted in your environment, reference from windows registry).
 
Thanks and regards

**Comment by jolwaterman** [comment]
[](url)
<img width="459" alt="2023-02-19 10_31_00-DISM GUI" src="https://user-images.githubusercontent.com/78624150/219954752-f3434c69-8f22-493b-8c09-b70558fd5ebd.png">

This is what I get.
I have to manually input the index number as "1" for it to work. 
I also don't get the "Use Mounted Image Option" even when I refresh the mounted image.
In the other Tabs, I have to copy and paste the mount folder.

I am not complaining, this is an AMAZING program and I can tell you worked really hard on it.
Thanks again!

I will look through the code and see if I can figure it out

**Comment by Dede333** [comment]
Hi,
you are right !, it's a bug, there is new release.
Thanks and regards

![Capt_fixe](https://user-images.githubusercontent.com/61848651/220191481-de70bf16-b946-4a14-a0bd-71f794d9213c.PNG)

**Comment by jolwaterman** [comment]
Thank you so much! I will be using this now
