### ISSUE TITLE
There are two questions.

### ISSUE THREAD

**Issue by ghost** [Dede333/VB_DISMGUI#5]
Hello,

1.There's nothing in the index.
![新點陣圖影像](https://github.com/Dede333/VB_DISMGUI/assets/138014001/7f8be545-bda2-4cf1-ac02-af5300a3fdcb)
I downloaded this version.
https://github.com/Dede333/VB_DISMGUI/releases/tag/21

2."Driver+Package+Feature" can you please add support for batch edit add delete function?

**Comment by Dede333** [comment]
Hello,
First, excuse me for my little english.


1)
You are right, extract index fonctionality is sensitive to the culture and langage environment (because it's hard coded).
You, can manually enter the index value on item directly and check if it’s ok.

2)
Yes, it’s possible, but you have to ask yourself the question how to create the batch, from a file, possibility of creating the file, nature of the text or csv file and more…
Why not !


Many thanks for your feedback.


De : e-tw ***@***.***>
Envoyé : dimanche 25 février 2024 05:46
À : Dede333/VB_DISMGUI ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [Dede333/VB_DISMGUI] There are two questions. (Issue #5)


Hello,

1.There's nothing in the index.
default.png (view on web)<https://github.com/Dede333/VB_DISMGUI/assets/138014001/7f8be545-bda2-4cf1-ac02-af5300a3fdcb>
I downloaded this version.
https://github.com/Dede333/VB_DISMGUI/releases/tag/21

2."Driver+Package+Functionality" can you please add support for batch edit add delete function?

**Comment by Dede333** [comment]
Hi,
can you check the latest release (tag 22) and see if it's good for you ?
Thanks and regards.

**Comment by ghost** [comment]
HI,Okay, that's fine. Just keep it simple and easy to use.
@Dede333

**Comment by Dede333** [comment]
> HI,Okay, that's fine. Just keep it simple and easy to use. @Dede333

Many thanks for your feedback !
